### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by knownasilya** [toranb/ember-redux-example#1]
Have you seen https://github.com/AltSchool/ember-cli-redux, maybe it's worth joining efforts there.

**Comment by toranb** [comment]
The only open issue in fact :)

https://github.com/AltSchool/ember-cli-redux/issues/1

**Comment by toranb** [comment]
At this time I'm just trying to understand what this looks like - that was the only redux project for ember right now but it may not be what I end up with (who knows yet -early days with this tech).

**Comment by knownasilya** [comment]
Ah, yes. Interesting conversation in that other issue. Thanks for tackling this.

**Comment by toranb** [comment]
It got even more interesting today as I dropp'd both a "connected" route func and fully async master/detail example :)
